/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/copilotkit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copilotkit Agent Endpoint
         * @description AG-UI direct agent endpoint for CopilotKit frontend.
         */
        post: operations["copilotkit_agent_endpoint_api_copilotkit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/copilotkit/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copilotkit Health
         * @description Health check for CopilotKit agent endpoint.
         */
        get: operations["copilotkit_health_api_copilotkit_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chat Threads
         * @description List past chat sessions stored in the agent checkpoint DB.
         */
        get: operations["list_chat_threads_api_chat_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Thread Messages
         * @description Return AG-UI-friendly messages for a checkpoint thread.
         */
        get: operations["get_chat_thread_messages_api_chat_threads__thread_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Chat Thread
         * @description Delete a chat thread's checkpoints.
         */
        delete: operations["delete_chat_thread_api_chat_threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fe-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Frontend Settings
         * @description Return saved frontend default settings (layers / global). Empty when unset.
         */
        get: operations["get_frontend_settings_api_fe_settings_get"];
        put?: never;
        /**
         * Save Frontend Settings
         * @description Partial-merge save of frontend default settings.
         *
         *     - `{"layers": {"<id>": {"defaultOpacity": 0.6}}}` → そのキーのみ上書き
         *     - null 送信でその保存済みキー/レイヤを削除(カタログ既定へ戻す)
         *     - 返り値は保存後の全体設定
         *
         *     ボディは意図的に pydantic モデル化しない (update: dict)。null = 保存済み
         *     キーの削除 (既定へ戻す) という部分マージ契約を保持するためで、値の
         *     バリデーションは fe_settings 側で行い、違反は 400 で返す。
         */
        post: operations["save_frontend_settings_api_fe_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map Viewer
         * @description Serves the main map viewer application HTML (React index.html or fallback map_viewer.html).
         */
        get: operations["get_map_viewer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geojson Api
         * @description Returns property search results directly formatted as a GeoJSON FeatureCollection.
         *     If map_viewer.html falls back to map.geojson, this serves the same endpoint.
         *
         *     このフィルタパラメータは CLI / MCP 用。FE は /api/geojson/stream で全件を
         *     取得し client-side worker で完全フィルタする。
         */
        get: operations["get_geojson_api_api_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geojson Api
         * @description Returns property search results directly formatted as a GeoJSON FeatureCollection.
         *     If map_viewer.html falls back to map.geojson, this serves the same endpoint.
         *
         *     このフィルタパラメータは CLI / MCP 用。FE は /api/geojson/stream で全件を
         *     取得し client-side worker で完全フィルタする。
         */
        get: operations["get_geojson_api_map_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geojson/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geojson Stream Api
         * @description 物件GeoJSONを1行ずつ流すNDJSONストリーム。初期ロード進捗表示用。
         *
         *     行契約 (StreamingResponse のため response_model は持たない):
         *     - 1行目: {"type": "meta", "total": <int>}
         *     - 中間行: {"type": "feature", "feature": <PropertyFeature>}
         *     - 末尾行: {"type": "end", "count": <int>}
         *     feature の型は GET /api/geojson (PropertyGeoJSON) と同一。
         *
         *     注意: meta.total は上限概算値。post filter (max_walk_minutes /
         *     required_features / max_monthly_total_yen) が未反映な上、座標欠落物件を
         *     スキップするため end.count と一致する保証がない。
         */
        get: operations["get_geojson_stream_api_api_geojson_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/kml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Kml Api
         * @description 指定物件 ID 群を Google Earth 用 KML としてダウンロードさせる.
         *
         *     FE の表示中リスト(フィルタ適用済み)をそのまま出力する想定のため、
         *     is_active や shortlist 状態による絞り込みは行わない。
         */
        post: operations["export_kml_api_api_export_kml_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Property Detail Api
         * @description Gets detailed information for a single property.
         *
         *     by=auto(既定) は数字キーを properties.id として優先解決する。room_id
         *     (external_id) で引く場合は by=external を指定し、複数ソースに存在する
         *     room_id では source(=source_site) も指定する。
         */
        get: operations["get_property_detail_api_api_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/price-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price Trend Api
         * @description 日次の価格変動推移(中央値/平均/掲載物件数/値下げ・値上げ件数)を返す.
         *
         *     全プロバイダ分を一括返却し、FE 側で「すべて/プロバイダ別」を切替える。
         *     prefecture_name 指定時は物件分析モーダルの「同都道府県の市場中央値」用に
         *     その県の物件のみで集計する(空文字列は未指定扱いで全県)。
         */
        get: operations["get_price_trend_api_api_analysis_price_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{property_id}/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Shortlist Api
         * @description Updates shortlist status (saved, hide, reject, or None).
         *
         *     解決ロジックは詳細取得と共通(id 優先)。external_id が複数ソースにまたがる
         *     場合は 409 を返し、推測で更新しない。
         */
        post: operations["update_shortlist_api_api_properties__property_id__shortlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Status
         * @description Gets statistics and background scheduler/scraper status.
         */
        get: operations["get_admin_status_api_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Sources
         * @description List ingest sources for admin UI (catalog + registry + counts).
         */
        get: operations["get_admin_sources_api_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scrape-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Scrape Settings
         * @description ソース別スクレイプ設定(取得間隔/制限時クールダウン)の実効値を返す。
         */
        get: operations["get_admin_scrape_settings_api_admin_scrape_settings_get"];
        put?: never;
        /**
         * Save Admin Scrape Settings
         * @description ソース別スクレイプ設定の部分マージ保存(null で該当キーを既定へ戻す)。
         *
         *     ボディは意図的に pydantic モデル化しない (update: dict)。null = 保存済み
         *     キーの削除 (既定へ戻す) という部分マージ契約を保持するためで、値の
         *     バリデーションは scrape_settings 側で行い、違反は 400 で返す。
         *     返り値は部分マージ後の保存値全体 (defaults / saved は null)。
         */
        post: operations["save_admin_scrape_settings_api_admin_scrape_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scrape
         * @description Trigger multi-source v2 scrape (per-source or bulk).
         */
        post: operations["trigger_scrape_api_admin_scrape_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rotation Status
         * @description 県ローテーション・スケジュールの状態（admin UI 用・読み取り専用）.
         */
        get: operations["get_rotation_status_api_admin_rotation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rotation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Rotation Run
         * @description 手動で県ローテーション・スクレイプを1ソース分実行する.
         *
         *     daily_limit / default_est はジョブ側で実行時に解決する。
         */
        post: operations["trigger_rotation_run_api_admin_rotation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rotation-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Rotation Settings
         * @description ソース別ローテーション設定(日次上限/既定1県件数)の実効値を返す。
         */
        get: operations["get_admin_rotation_settings_api_admin_rotation_settings_get"];
        put?: never;
        /**
         * Save Admin Rotation Settings
         * @description ソース別ローテーション設定の部分マージ保存(null で該当キーを既定へ戻す)。
         *
         *     ボディは意図的に pydantic モデル化しない (update: dict)。null = 保存済み
         *     キーの削除 (既定へ戻す) という部分マージ契約を保持するためで、値の
         *     バリデーションは rotation_settings 側で行い、違反は 400 で返す。
         *     返り値は部分マージ後の保存値全体 (defaults / saved は null)。
         */
        post: operations["save_admin_rotation_settings_api_admin_rotation_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Geocode
         * @description Triggers geocoding of v2 properties in the background (spec §3.3 modes).
         */
        post: operations["trigger_geocode_api_admin_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{code}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tile
         * @description PMTiles から指定 ZXY タイルを取り出して返す.
         */
        get: operations["get_tile_api_tiles__code___z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMessage
         * @description An activity progress message emitted between chat messages.
         */
        ActivityMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "activity";
            /** Activitytype */
            activityType: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** AdminDbStats */
        AdminDbStats: {
            /** Total Properties */
            total_properties: number;
            /** Missing Coordinates */
            missing_coordinates: number;
            /**
             * Shortlist
             * @description 状態→件数マップ
             * @default {}
             */
            shortlist: {
                [key: string]: number;
            };
            /**
             * By Source
             * @description source_site→件数マップ
             * @default {}
             */
            by_source: {
                [key: string]: number;
            };
        };
        /** AdminHttpInfo */
        AdminHttpInfo: {
            /** Mode */
            mode: string;
            /** Proxy Enabled */
            proxy_enabled: boolean;
        };
        /**
         * AdminSourceInfo
         * @description GET /api/admin/sources の sources 要素 1 件。
         */
        AdminSourceInfo: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled: boolean;
            /** Registered */
            registered: boolean;
            /** Available */
            available: boolean;
            /**
             * Prefectures
             * @default []
             */
            prefectures: string[];
            /**
             * Targets
             * @default []
             */
            targets: components["schemas"]["AdminTargetInfo"][];
            /** Default Pages */
            default_pages?: number | null;
            /** Default All Pages */
            default_all_pages?: boolean | null;
            /** Supports All Pages */
            supports_all_pages?: boolean | null;
            /** Default Mark Inactive */
            default_mark_inactive?: boolean | null;
            counts: components["schemas"]["AdminTargetCounts"];
        };
        /** AdminSourcesResponse */
        AdminSourcesResponse: {
            /** Sources */
            sources: components["schemas"]["AdminSourceInfo"][];
        };
        /**
         * AdminStatsResponse
         * @description GET /api/admin/status の応答。
         */
        AdminStatsResponse: {
            task_status: components["schemas"]["TaskStatus"];
            /**
             * Recent Runs
             * @default []
             */
            recent_runs: components["schemas"]["ScrapeRunSummary"][];
            http: components["schemas"]["AdminHttpInfo"];
            transfer?: components["schemas"]["TransferSnapshot"] | null;
            db_stats: components["schemas"]["AdminDbStats"];
        };
        /** AdminTargetCounts */
        AdminTargetCounts: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Missing Coords */
            missing_coords: number;
        };
        /**
         * AdminTargetInfo
         * @description ソース配下のクロール対象 (通常は県) 1 件。
         */
        AdminTargetInfo: {
            /** Key */
            key: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            counts: components["schemas"]["AdminTargetCounts"];
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Last Detail Scraped At */
            last_detail_scraped_at?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Run Status */
            last_run_status?: string | null;
            /** Last Run List Items */
            last_run_list_items?: number | null;
            /** Last Run Detail Ok */
            last_run_detail_ok?: number | null;
            /** Has Data */
            has_data: boolean;
        };
        /**
         * AssistantMessage
         * @description An assistant message.
         */
        AssistantMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * AudioInputContent
         * @description An audio input content fragment.
         */
        AudioInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BinaryInputContent
         * @description A deprecated binary payload reference in a multimodal user message.
         */
        BinaryInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Mimetype */
            mimeType: string;
            /** Id */
            id?: string | null;
            /** Url */
            url?: string | null;
            /** Data */
            data?: string | null;
            /** Filename */
            filename?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Campaign
         * @description 物件に紐づくキャンペーン 1 件 (campaigns テーブル行 + legacy エイリアス)。
         *
         *     starts_on / ends_on は ISO 日付 (未記載は null)。ends_on が null の場合は
         *     期間未記載 (継続 or 不明) を示す。
         */
        Campaign: {
            /** Id */
            id?: number | null;
            /** Property Id */
            property_id?: number | null;
            /**
             * Campaign Type
             * @description キャンペーン型
             */
            campaign_type?: string | null;
            /**
             * Title
             * @description 見出し
             */
            title?: string | null;
            /**
             * Content
             * @description 本文
             */
            content?: string | null;
            /**
             * Target Period Text
             * @description 対象期間の生テキスト
             */
            target_period_text?: string | null;
            /**
             * Target Condition Text
             * @description 対象条件の生テキスト
             */
            target_condition_text?: string | null;
            /**
             * Starts On
             * @description 開始日 (YYYY-MM-DD)
             */
            starts_on?: string | null;
            /**
             * Ends On
             * @description 終了日 (YYYY-MM-DD). null=期間未記載
             */
            ends_on?: string | null;
            /**
             * Target Plan Key
             * @description 対象プランキー (空=全プラン)
             */
            target_plan_key?: string | null;
            /**
             * Target Plan Code
             * @description target_plan_key のエイリアス (legacy 同義キー。現状維持)
             */
            target_plan_code?: string | null;
            /**
             * Discount Unit
             * @description 割引単位 (yen / percent / package / pokkiri 等)
             */
            discount_unit?: string | null;
            /**
             * Discount Value
             * @description 割引量 (単位は discount_unit)
             */
            discount_value?: number | null;
            /**
             * Discount Max Yen
             * @description 割引上限円
             */
            discount_max_yen?: number | null;
            /**
             * Period Max Days
             * @description 適用期間上限日数
             */
            period_max_days?: number | null;
            /**
             * Stay Min Days
             * @description 適用最少滞在日数
             */
            stay_min_days?: number | null;
            /**
             * Stay Max Days
             * @description 適用最大滞在日数
             */
            stay_max_days?: number | null;
            /**
             * Contract Within Days
             * @description 契約期限 (n 日以内)
             */
            contract_within_days?: number | null;
            /**
             * Package Rent Benefit Yen
             * @description パッケ 適用の家賃相当優待円
             */
            package_rent_benefit_yen?: number | null;
            /**
             * Package Cleaning Benefit Yen
             * @description パッケ適用の清掃費優待円
             */
            package_cleaning_benefit_yen?: number | null;
            /**
             * Package Fee Benefit Yen
             * @description パッケ適用の手数料優待円
             */
            package_fee_benefit_yen?: number | null;
            /**
             * Package Total Benefit Yen
             * @description パッケ適用の優待合計円
             */
            package_total_benefit_yen?: number | null;
            /**
             * Structure Source
             * @description 構造化の由来 (llm / mechanical 等)
             */
            structure_source?: string | null;
            /**
             * Parse Ok
             * @description 構造化成功フラグ (0/1)
             */
            parse_ok?: number | null;
            /**
             * Parse Warnings
             * @description 構造化時の警告 (JSON)
             */
            parse_warnings?: string | null;
            /**
             * Raw Json
             * @description 抽出元の生 JSON
             */
            raw_json?: string | null;
            /**
             * Scraped At
             * @description 取得日時
             */
            scraped_at?: string | null;
        };
        /** ChatThreadDeleteResponse */
        ChatThreadDeleteResponse: {
            /**
             * Status
             * @description success / error
             */
            status: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Message
             * @description error 時の詳細
             */
            message?: string | null;
        };
        /**
         * ChatThreadMessage
         * @description AG-UI 向けに正規化したメッセージ 1 件。
         */
        ChatThreadMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @description user / assistant
             */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatThreadMessagesResponse */
        ChatThreadMessagesResponse: {
            /** Threadid */
            threadId: string;
            /** Messages */
            messages: components["schemas"]["ChatThreadMessage"][];
        };
        /**
         * ChatThreadSummary
         * @description チャットセッション 1 件 (チェックポイント DB 由来)。
         */
        ChatThreadSummary: {
            /** Id */
            id: string;
            /** Checkpointcount */
            checkpointCount: number;
            /** Title */
            title: string;
            /** Preview */
            preview: string;
            /** Updatedat */
            updatedAt?: string | null;
            /** Messagecount */
            messageCount: number;
        };
        /** ChatThreadsResponse */
        ChatThreadsResponse: {
            /** Threads */
            threads: components["schemas"]["ChatThreadSummary"][];
        };
        /**
         * Context
         * @description Additional context for the agent.
         */
        Context: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * DeveloperMessage
         * @description A developer message.
         */
        DeveloperMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DocumentInputContent
         * @description A document input content fragment.
         */
        DocumentInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FeGlobalSettings
         * @description アプリ全体の表示設定。
         */
        FeGlobalSettings: {
            /**
             * Pinclustering
             * @description 物件ピンのクラスタリング (未指定/null = true)
             */
            pinClustering?: boolean | null;
        };
        /**
         * FeLayerOverrides
         * @description レイヤ 1 件分の保存済みデフォルト上書き (未指定キーはカタログ既定へフォールバック)。
         */
        FeLayerOverrides: {
            /**
             * Defaultopacity
             * @description レイヤ追加時のデフォルト透明度 (0-1)
             */
            defaultOpacity?: number | null;
            /**
             * Clustering
             * @description クラスタリング対応レイヤ (oshima) のクラスタ表示
             */
            clustering?: boolean | null;
        };
        /**
         * FeSettingsResponse
         * @description GET/POST /api/fe-settings の応答 (フロントエンド既定値設定)。
         *
         *     契約型は frontend/src/lib/feSettings.ts の FeSettings と整合する。
         *     layers は layerId → 上書きの自由 dict。POST は部分マージ後の全体を返す。
         */
        FeSettingsResponse: {
            /**
             * Layers
             * @default {}
             */
            layers: {
                [key: string]: components["schemas"]["FeLayerOverrides"];
            };
            /** @description アプリ全体の表示設定 (global は Python 予約語のため属性名は global_) */
            global?: components["schemas"]["FeGlobalSettings"];
        };
        /**
         * FunctionCall
         * @description Name and arguments of a function call.
         */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * GeoJSONPoint
         * @description Point ジオメトリ。coordinates は [lng, lat]。
         */
        GeoJSONPoint: {
            /**
             * Type
             * @constant
             */
            type: "Point";
            /** Coordinates */
            coordinates: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /api/copilotkit/health。
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * ImageInputContent
         * @description An image input content fragment.
         */
        ImageInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentDataSource
         * @description Inline base64-encoded source.
         */
        InputContentDataSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "data";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentUrlSource
         * @description URL-referenced source.
         */
        InputContentUrlSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * KmlExportRequest
         * @description Body for KML export (/api/export/kml).
         */
        KmlExportRequest: {
            /** Ids */
            ids: number[];
        };
        /**
         * PriceHistoryMeta
         * @description 価格履歴の品質ガード開示メタ (破損値除外件数)。
         */
        PriceHistoryMeta: {
            /** Total Count */
            total_count: number;
            /** Dropped Count */
            dropped_count: number;
            /** First At */
            first_at?: string | null;
            /** Last At */
            last_at?: string | null;
        };
        /**
         * PriceHistoryPoint
         * @description 価格履歴 1 点 (品質ガード適用後の割引日額)。
         */
        PriceHistoryPoint: {
            /** Scraped At */
            scraped_at: string;
            /** Min Discounted Daily Rent Yen */
            min_discounted_daily_rent_yen: number;
            /** Min Discounted Monthly Total Yen */
            min_discounted_monthly_total_yen?: number | null;
        };
        /**
         * PriceTrendMeta
         * @description 品質ガードの適用状況。
         */
        PriceTrendMeta: {
            /** Snapshot Rows */
            snapshot_rows: number;
            /** Guarded Rows */
            guarded_rows: number;
            /** Excluded Rows */
            excluded_rows: number;
        };
        /**
         * PriceTrendPoint
         * @description 価格変動の日次集計 1 点。
         */
        PriceTrendPoint: {
            /**
             * Date
             * @description YYYY-MM-DD
             */
            date: string;
            /**
             * Median
             * @description 日額中央値 (円)
             */
            median: number;
            /**
             * Avg
             * @description 日額平均 (円)
             */
            avg: number;
            /**
             * Count
             * @description 代表値が存在する物件数
             */
            count: number;
            /**
             * Down
             * @description 直前代表値比で値下げした物件数
             */
            down: number;
            /**
             * Up
             * @description 直前代表値比で値上げした物件数
             */
            up: number;
        };
        /** PriceTrendProvider */
        PriceTrendProvider: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * PriceTrendResponse
         * @description GET /api/analysis/price-trend の応答 (全プロバイダ分を一括返却)。
         */
        PriceTrendResponse: {
            /**
             * Days
             * @description 集計期間 (日数)
             */
            days: number;
            /**
             * Carried Window Days
             * @description 前進補完で既知値とみなす窓 (日数)
             */
            carried_window_days: number;
            /** Generated At */
            generated_at: string;
            /** Providers */
            providers: components["schemas"]["PriceTrendProvider"][];
            series: components["schemas"]["PriceTrendSeries"];
            meta: components["schemas"]["PriceTrendMeta"];
        };
        /**
         * PriceTrendSeries
         * @description carried=前進補完推計 / scraped=当日取得分。
         */
        PriceTrendSeries: {
            carried: components["schemas"]["PriceTrendSeriesSet"];
            scraped: components["schemas"]["PriceTrendSeriesSet"];
        };
        /**
         * PriceTrendSeriesSet
         * @description 1 モード分の系列 (全プロバイダ統合 + プロバイダ別)。
         */
        PriceTrendSeriesSet: {
            /** All */
            all: components["schemas"]["PriceTrendPoint"][];
            /**
             * By Site
             * @description キー=source_site id
             * @default {}
             */
            by_site: {
                [key: string]: components["schemas"]["PriceTrendPoint"][];
            };
        };
        /**
         * PropertyAccessInfo
         * @description アクセス 1 行 (交通)。
         */
        PropertyAccessInfo: {
            /**
             * Line Name
             * @description 路線名
             */
            line_name?: string | null;
            /**
             * Station Name
             * @description 駅名
             */
            station_name?: string | null;
            /**
             * Walk Minutes
             * @description 徒歩分数
             */
            walk_minutes?: number | null;
            /**
             * Raw Text
             * @description 抽出元の生テキスト
             */
            raw_text?: string | null;
        };
        /**
         * PropertyDetailResponse
         * @description GET /api/properties/{property_id} の応答。
         *
         *     properties テーブル行 (SELECT * の全列) + 子テーブル (accesses / images /
         *     links / features / campaigns / rent_plans / shortlist / price_history)。
         */
        PropertyDetailResponse: {
            /** Id */
            id: number;
            /** Source Site */
            source_site: string;
            /** External Id */
            external_id: string;
            /**
             * Entity Type
             * @default room
             */
            entity_type: string;
            /** Parent Property Id */
            parent_property_id?: number | null;
            /** Title */
            title?: string | null;
            /** Detail Url */
            detail_url?: string | null;
            /** Prefecture Slug */
            prefecture_slug?: string | null;
            /** Prefecture Name */
            prefecture_name?: string | null;
            /**
             * Municipality
             * @description 市区町村 (相場比較のピア grouping 用)
             */
            municipality?: string | null;
            /** Address */
            address?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Geocode Source */
            geocode_source?: string | null;
            /** Geocode Confidence */
            geocode_confidence?: number | null;
            /** Layout */
            layout?: string | null;
            /** Area M2 */
            area_m2?: number | null;
            /** Area M2 Max */
            area_m2_max?: number | null;
            /** Built Year */
            built_year?: number | null;
            /** Built Month */
            built_month?: number | null;
            /** Construction Year Text */
            construction_year_text?: string | null;
            /** Capacity Text */
            capacity_text?: string | null;
            /** Structure */
            structure?: string | null;
            /** Floors Text */
            floors_text?: string | null;
            /** Floor Number */
            floor_number?: string | null;
            /**
             * Point Text
             * @description 物件紹介文 (POINT)
             */
            point_text?: string | null;
            /** Availability Text */
            availability_text?: string | null;
            /** Min Stay Days */
            min_stay_days?: number | null;
            /** Contract Fee Yen */
            contract_fee_yen?: number | null;
            /**
             * First Seen At
             * @description 初回検知日時 (掲載日数の算出に使用)
             */
            first_seen_at?: string | null;
            /**
             * Last Seen At
             * @description 最終確認日時 (掲載終了時の参考値基準)
             */
            last_seen_at?: string | null;
            /** Detail Scraped At */
            detail_scraped_at?: string | null;
            /**
             * Is Active
             * @description false = サイト掲載終了 (価格等は最終取得時点の参考値)
             * @default true
             */
            is_active: boolean;
            /** Catalog Rent Per Day Yen */
            catalog_rent_per_day_yen?: number | null;
            /** Catalog Total Hint Yen */
            catalog_total_hint_yen?: number | null;
            /**
             * Total Score
             * @description 総合スコア (スコアリング再活用予定のため維持)
             */
            total_score?: number | null;
            /** Rent Score */
            rent_score?: number | null;
            /** Walk Score */
            walk_score?: number | null;
            /** Area Score */
            area_score?: number | null;
            /** Age Score */
            age_score?: number | null;
            /** Commute Score */
            commute_score?: number | null;
            /**
             * Source Property Id
             * @description external_id のエイリアス
             */
            source_property_id?: string | null;
            /**
             * Source Display Name
             * @description ソースの表示名
             * @default
             */
            source_display_name: string;
            /**
             * Accesses
             * @default []
             */
            accesses: components["schemas"]["PropertyAccessInfo"][];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["PropertyImageInfo"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["PropertyLinkInfo"][];
            /**
             * Features
             * @default []
             */
            features: components["schemas"]["PropertyFeatureInfo"][];
            /**
             * Campaigns
             * @default []
             */
            campaigns: components["schemas"]["Campaign"][];
            /**
             * Rent Plans
             * @default []
             */
            rent_plans: components["schemas"]["RentPlan"][];
            shortlist?: components["schemas"]["ShortlistInfo"] | null;
            /**
             * Price History
             * @default []
             */
            price_history: components["schemas"]["PriceHistoryPoint"][];
            price_history_meta?: components["schemas"]["PriceHistoryMeta"] | null;
        };
        /**
         * PropertyFeature
         * @description GeoJSON Feature 1 件 (Point)。
         */
        PropertyFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["GeoJSONPoint"];
            properties: components["schemas"]["PropertyProperties"];
        };
        /**
         * PropertyFeatureInfo
         * @description 設備 1 件。
         */
        PropertyFeatureInfo: {
            /** Feature Name */
            feature_name: string;
            /**
             * Feature Category
             * @description building / room 等の分類
             */
            feature_category?: string | null;
        };
        /**
         * PropertyGeoJSON
         * @description GET /api/geojson の FeatureCollection 応答。
         */
        PropertyGeoJSON: {
            /**
             * Type
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["PropertyFeature"][];
        };
        /**
         * PropertyImageInfo
         * @description 画像 1 枚。
         */
        PropertyImageInfo: {
            /** Image Url */
            image_url: string;
            /**
             * Image Type
             * @description thumbnail / gallery / other
             */
            image_type?: string | null;
            /** Alt Text */
            alt_text?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /**
         * PropertyLinkInfo
         * @description 関連リンク 1 件。
         */
        PropertyLinkInfo: {
            /** Link Type */
            link_type: string;
            /** Url */
            url: string;
            /** Label */
            label?: string | null;
        };
        /**
         * PropertyProperties
         * @description GeoJSON Feature の properties (検索結果 1 物件分)。
         *
         *     一括 /api/geojson と /api/geojson/stream の feature 行で同一ペイロード。
         */
        PropertyProperties: {
            /** Id */
            id: number;
            /**
             * Room Id
             * @description external_id のエイリアス (legacy)
             */
            room_id?: string | null;
            /** Source Site */
            source_site?: string | null;
            /** Source Display Name */
            source_display_name?: string | null;
            /** Title */
            title?: string | null;
            /** Detail Url */
            detail_url?: string | null;
            /** Address */
            address?: string | null;
            /** Prefecture Name */
            prefecture_name?: string | null;
            /** Municipality */
            municipality?: string | null;
            /** Layout */
            layout?: string | null;
            /** Area M2 */
            area_m2?: number | null;
            /**
             * Min Daily Rent
             * @description 最安実効日額 (as-of-today)
             */
            min_daily_rent?: number | null;
            /**
             * Min Plan Total
             * @description 最安プランの 30 日換算総額
             */
            min_plan_total?: number | null;
            /** Min Plan Name */
            min_plan_name?: string | null;
            /** Min Walk Minutes */
            min_walk_minutes?: number | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /**
             * Images
             * @description 画像 URL のリスト
             * @default []
             */
            images: string[];
            /**
             * Total Score
             * @description 総合スコア (スコアリング再活用予定のため維持)
             */
            total_score?: number | null;
            /**
             * Shortlist Status
             * @description saved / hide / reject / none
             * @default none
             */
            shortlist_status: string;
            /**
             * Is Active
             * @description false = サイト掲載終了
             * @default true
             */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at?: string | null;
            /**
             * Access Summary
             * @description カンマ区切りのアクセス要約
             * @default
             */
            access_summary: string;
            /**
             * Feature Summary
             * @description カンマ区切りの設備要約
             * @default
             */
            feature_summary: string;
            /**
             * Station Summary
             * @description カンマ区切りの駅名要約
             * @default
             */
            station_summary: string;
            /** Point Text */
            point_text?: string | null;
            /**
             * Rent Plans
             * @default []
             */
            rent_plans: components["schemas"]["RentPlan"][];
            /**
             * Campaigns
             * @default []
             */
            campaigns: components["schemas"]["Campaign"][];
        };
        /**
         * ReasoningMessage
         * @description A reasoning message containing the agent's internal reasoning process.
         */
        ReasoningMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "reasoning";
            /** Content */
            content: string;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RentPlan
         * @description 物件の料金プラン 1 件。
         *
         *     金額の原単位は presentation_unit (per_day / per_month 等)。
         *     ``*_daily_rent_yen`` は日額換算 (整数・切捨て)、
         *     ``*_total_yen`` は 30 日換算の概算総額 (日額 + 共益費日額) x 30。
         *
         *     ``effective_*`` 系 (effective_rent_yen / effective_daily_rent_yen /
         *     effective_total_yen / effective_campaign_label) は **基準日 =
         *     as-of-today (今日) でキャンペーンを解決した値**。有効キャンペーンが
         *     あれば割引後、無ければ通常価格 (rent_current_yen → rent_original_yen)
         *     にフォールバックする。滞在期間 (check-in/check-out) を基準にした試算は
         *     この契約には含まれず、FE 側の rentCalculator が別途計算する。
         */
        RentPlan: {
            /**
             * Plan Key
             * @description プランキー (property_id 内で一意)
             */
            plan_key?: string | null;
            /**
             * Plan Code
             * @description plan_key のエイリアス (FE/legacy 同義キー。現状維持)
             */
            plan_code?: string | null;
            /**
             * Plan Name
             * @description プラン名
             */
            plan_name?: string | null;
            /**
             * Duration Text
             * @description plan_name のエイリアス (legacy 同義キー。現状維持)
             */
            duration_text?: string | null;
            /**
             * Duration Min Days
             * @description 最短滞在日数
             */
            duration_min_days?: number | null;
            /**
             * Duration Max Days
             * @description 最長滞在日数 (無期限は null)
             */
            duration_max_days?: number | null;
            /**
             * Available
             * @description 取扱ありフラグ
             * @default true
             */
            available: boolean;
            /**
             * Campaign Label
             * @description プラン行に付記されたキャンペーンラベル
             */
            campaign_label?: string | null;
            /**
             * Presentation Unit
             * @description 金額の原単位 (per_day / per_month)
             * @default per_day
             */
            presentation_unit: string;
            /**
             * Rent Original Yen
             * @description 定価 (presentation_unit 原単位)
             */
            rent_original_yen?: number | null;
            /**
             * Rent Current Yen
             * @description 現行価格 (同上)
             */
            rent_current_yen?: number | null;
            /**
             * Management Yen
             * @description 共益費 (同上)
             */
            management_yen?: number | null;
            /**
             * Utilities Yen
             * @description 水光熱費 (同上)
             */
            utilities_yen?: number | null;
            /**
             * Utilities Included
             * @description 水光熱費込みフラグ
             * @default true
             */
            utilities_included: boolean;
            /**
             * Cleaning Yen
             * @description 清掃費 (同上)
             */
            cleaning_yen?: number | null;
            /**
             * Original Daily Rent Yen
             * @description 定価の日額換算
             */
            original_daily_rent_yen?: number | null;
            /**
             * Discounted Daily Rent Yen
             * @description 現行価格の日額換算
             */
            discounted_daily_rent_yen?: number | null;
            /**
             * Management Fee Daily Yen
             * @description 共益費の日額換算 (無ければ 0)
             * @default 0
             */
            management_fee_daily_yen: number;
            /**
             * Cleaning Fee Yen
             * @description cleaning_yen のエイリアス
             */
            cleaning_fee_yen?: number | null;
            /**
             * Raw Text
             * @description 抽出元の生テキスト
             */
            raw_text?: string | null;
            /**
             * Original Total Yen
             * @description 定価の 30 日換算総額 ( rent+共益 )
             */
            original_total_yen?: number | null;
            /**
             * Discounted Total Yen
             * @description 現行価格の 30 日換算総額
             */
            discounted_total_yen?: number | null;
            /**
             * Total Period Days
             * @description 総額換算の基準日数 (固定 30)
             * @default 30
             */
            total_period_days: number;
            /**
             * Effective Rent Yen
             * @description as-of-today で解決した実効価格 (presentation_unit 原単位)
             */
            effective_rent_yen?: number | null;
            /**
             * Effective Daily Rent Yen
             * @description as-of-today で解決した実効日額
             */
            effective_daily_rent_yen?: number | null;
            /**
             * Effective Total Yen
             * @description as-of-today の実効日額による 30 日換算総額 (日額未確定なら null)
             */
            effective_total_yen?: number | null;
            /**
             * Campaign Applied
             * @description as-of-today でキャンペーン割引が適用中か
             * @default false
             */
            campaign_applied: boolean;
            /**
             * Campaign Expired
             * @description 参照したキャンペーンが期限切れか
             * @default false
             */
            campaign_expired: boolean;
            /**
             * Effective Campaign Label
             * @description as-of-today で有効なキャンペーンの表示ラベル
             */
            effective_campaign_label?: string | null;
            /**
             * Expired Campaign Label
             * @description 期限切れで参照されたキャンペーンの表示ラベル
             */
            expired_campaign_label?: string | null;
            /**
             * Matched Campaign Type
             * @description 適合したキャンペーン型 (discount / package 等)
             */
            matched_campaign_type?: string | null;
        };
        /**
         * RotationBatchPreview
         * @description 次回実行バッチのプレビュー。
         */
        RotationBatchPreview: {
            /**
             * Prefs
             * @description 対象県スラッグ (実行順)
             * @default []
             */
            prefs: string[];
            /**
             * Est Items
             * @description 予想取得件数
             * @default 0
             */
            est_items: number;
            /**
             * Unlimited
             * @description 1 県あたり予算上限を無視する単独県バッチか
             * @default false
             */
            unlimited: boolean;
            /**
             * Reason
             * @description バッチ内容の理由コード (空文字=通常バッチ)
             * @default
             */
            reason: string;
        };
        /**
         * RotationPrefStatus
         * @description 県ごとのローテーション状態。
         */
        RotationPrefStatus: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Known Total
             * @description 既知物件数 (未計測は null)
             */
            known_total?: number | null;
            /**
             * Last Full Ok At
             * @description 前回フル取得成功時刻
             */
            last_full_ok_at?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Consecutive Failures
             * @description 連続スクレイプ失敗数
             * @default 0
             */
            consecutive_failures: number;
            /**
             * Suppressed
             * @description 連続失敗によるクールダウン中か
             * @default false
             */
            suppressed: boolean;
            /**
             * Is Running
             * @description 現在スクレイプ実行中か
             * @default false
             */
            is_running: boolean;
            /**
             * Queue Position
             * @description 次回バッチの順番 (昇順で実行)
             */
            queue_position: number;
        };
        /**
         * RotationRunRequest
         * @description Body for manual rotation run.
         */
        RotationRunRequest: {
            /** Source */
            source: string;
        };
        /**
         * RotationRunStartResponse
         * @description POST /api/admin/rotation/run の起動応答。
         */
        RotationRunStartResponse: {
            /**
             * Status
             * @constant
             */
            status: "started";
            /** Task */
            task: string;
            /** Source */
            source: string;
        };
        /**
         * RotationSettingsDefaults
         * @description ローテーション設定のコード既定値。
         */
        RotationSettingsDefaults: {
            /**
             * Daily Limit
             * @description 1 日あたり取得上限の既定値 (件)
             */
            daily_limit: number;
            /**
             * Default Est
             * @description known_total 未計測県の予算見積り既定値 (件)
             */
            default_est: number;
        };
        /**
         * RotationSettingsResponse
         * @description GET /api/admin/rotation-settings の応答 (ソース別実効値一覧)。
         *
         *     POST /api/admin/rotation-settings は部分マージ後の「保存値」全体を返す
         *     現行契約のため、defaults と個別ソースの未保存キー / saved は null になる。
         */
        RotationSettingsResponse: {
            defaults?: components["schemas"]["RotationSettingsDefaults"] | null;
            /**
             * Sources
             * @description キー = SOURCE_CATALOG 由来の source id
             * @default {}
             */
            sources: {
                [key: string]: components["schemas"]["RotationSourceSettings"];
            };
        };
        /**
         * RotationSourceSettings
         * @description ソース 1 件分のローテーション設定 (実効値 or 保存値)。
         *
         *     GET (実効値一覧) では daily_limit / default_est は常に値入り。POST (部分
         *     マージ後の保存値) では保存済みキーのみ値入りで、未保存キーは null になる。
         */
        RotationSourceSettings: {
            /**
             * Daily Limit
             * @description 1 日あたり取得上限 (件)。実効値 = 保存値 > コード既定
             */
            daily_limit?: number | null;
            /**
             * Default Est
             * @description known_total 未計測県の予算見積り件数 (件)。実効値の優先順位は daily_limit と同一
             */
            default_est?: number | null;
            /**
             * Saved
             * @description DB 保存済みの上書き (未保存キーは欠損)。POST 応答 (保存値のみ) では null
             */
            saved?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RotationSourceStatus
         * @description ソースごとの県ローテーション状態。
         */
        RotationSourceStatus: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Cron
             * @description cron 式 (実行時刻)
             */
            cron: string;
            /**
             * Daily Limit
             * @description 1 日あたり取得上限の実効値
             */
            daily_limit: number;
            /** Used Today */
            used_today: number;
            /**
             * Default Est
             * @description 1 県あたりの既定取得件数の実効値
             */
            default_est: number;
            next_batch: components["schemas"]["RotationBatchPreview"];
            /** Prefs */
            prefs: components["schemas"]["RotationPrefStatus"][];
        };
        /**
         * RotationStatusResponse
         * @description GET /api/admin/rotation の応答。
         */
        RotationStatusResponse: {
            /** Sources */
            sources: components["schemas"]["RotationSourceStatus"][];
        };
        /**
         * RunAgentInput
         * @description Input for running an agent.
         */
        RunAgentInput: {
            /** Threadid */
            threadId: string;
            /** Runid */
            runId: string;
            /** Parentrunid */
            parentRunId?: string | null;
            /** State */
            state: unknown;
            /** Messages */
            messages: (components["schemas"]["DeveloperMessage"] | components["schemas"]["SystemMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["UserMessage"] | components["schemas"]["ToolMessage"] | components["schemas"]["ActivityMessage"] | components["schemas"]["ReasoningMessage"])[];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Context */
            context: components["schemas"]["Context"][];
            /** Forwardedprops */
            forwardedProps: unknown;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScrapeRequest
         * @description Body for multi-source v2 rescrape.
         */
        ScrapeRequest: {
            /** Sources */
            sources?: string[] | null;
            /**
             * Pages
             * @default 5
             */
            pages: number | null;
            /**
             * All Pages
             * @default false
             */
            all_pages: boolean;
            /** Max Details */
            max_details?: number | null;
            /**
             * List Only
             * @default false
             */
            list_only: boolean;
            /**
             * Mark Inactive
             * @default true
             */
            mark_inactive: boolean;
            /** Prefs */
            prefs?: string[] | null;
            /** Delay */
            delay?: number | null;
            /**
             * Geocode
             * @default true
             */
            geocode: boolean;
            /**
             * Geocode Limit
             * @default 200
             */
            geocode_limit: number;
        };
        /**
         * ScrapeRunSummary
         * @description スクレイプ run 1 件のサマリ (DB 由来・再起動後も残る)。
         */
        ScrapeRunSummary: {
            /** Id */
            id: number;
            /** Source Site */
            source_site: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Status */
            status: string;
            /** List Pages */
            list_pages?: number | null;
            /** List Items */
            list_items?: number | null;
            /** Detail Ok */
            detail_ok?: number | null;
            /** Detail Fail */
            detail_fail?: number | null;
            /** Error Summary */
            error_summary?: string | null;
        };
        /**
         * ScrapeSettingsDefaults
         * @description スクレイプ設定のコード既定値。
         */
        ScrapeSettingsDefaults: {
            /**
             * Delay Seconds
             * @description リクエスト間隔の既定値 (秒)
             */
            delay_seconds: number;
            /**
             * Cooldown Seconds
             * @description 制限検知時クールダウンの既定値 (秒)
             */
            cooldown_seconds: number;
        };
        /**
         * ScrapeSettingsResponse
         * @description GET /api/admin/scrape-settings の応答 (ソース別実効値一覧)。
         *
         *     POST /api/admin/scrape-settings は部分マージ後の「保存値」全体を返す
         *     現行契約のため、defaults と個別ソースの未保存キー / saved は null になる。
         */
        ScrapeSettingsResponse: {
            defaults?: components["schemas"]["ScrapeSettingsDefaults"] | null;
            /**
             * Sources
             * @description キー = SOURCE_CATALOG 由来の source id
             * @default {}
             */
            sources: {
                [key: string]: components["schemas"]["ScrapeSourceSettings"];
            };
        };
        /**
         * ScrapeSourceSettings
         * @description ソース 1 件分のスクレイプ設定 (実効値 or 保存値)。
         *
         *     GET (実効値一覧) では delay/cooldown は常に値入り。POST (部分マージ後の
         *     保存値) では保存済みキーのみ値入りで、未保存キーは null になる。
         */
        ScrapeSourceSettings: {
            /**
             * Delay Seconds
             * @description リクエスト間隔 (秒)。実効値 = 保存値 > config.json > コード既定
             */
            delay_seconds?: number | null;
            /**
             * Cooldown Seconds
             * @description 制限検知時クールダウン (秒)。実効値の優先順位は delay_seconds と同一
             */
            cooldown_seconds?: number | null;
            /**
             * Saved
             * @description DB 保存済みの上書き (未保存キーは欠損)。POST 応答 (保存値のみ) では null
             */
            saved?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ScrapeStartResponse
         * @description POST /api/admin/scrape の起動応答。
         */
        ScrapeStartResponse: {
            /**
             * Status
             * @constant
             */
            status: "started";
            /** Task */
            task: string;
            /**
             * Sources
             * @description 解決後の source id 群
             * @default []
             */
            sources: string[];
            /** Prefs */
            prefs?: string[] | null;
            /**
             * All Pages
             * @default false
             */
            all_pages: boolean;
            /** Pages */
            pages?: number | null;
            /**
             * Mark Inactive
             * @default true
             */
            mark_inactive: boolean;
        };
        /**
         * ShortlistInfo
         * @description ショートリスト状態 (未登録物件は null)。
         */
        ShortlistInfo: {
            /**
             * Status
             * @description saved / hide / reject
             */
            status: string;
            /** Comment */
            comment?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ShortlistUpdateRequest */
        ShortlistUpdateRequest: {
            /** Status */
            status: string;
            /** Comment */
            comment?: string | null;
        };
        /** ShortlistUpdateResponse */
        ShortlistUpdateResponse: {
            /**
             * Status
             * @constant
             */
            status: "success";
            /** Property Id */
            property_id?: number | null;
            /** Shortlist Status */
            shortlist_status: string;
        };
        /**
         * SystemMessage
         * @description A system message.
         */
        SystemMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TaskStartResponse
         * @description バックグラウンドタスク起動の共通応答。
         */
        TaskStartResponse: {
            /**
             * Status
             * @constant
             */
            status: "started";
            /** Task */
            task: string;
        };
        /**
         * TaskStatus
         * @description バックグラウンドタスクの実行状態 (プロセス内・再起動で消える)。
         */
        TaskStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "running";
            /** Current Task */
            current_task?: string | null;
            /** Last Run */
            last_run?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Last Result
             * @description 直前タスクの結果 (未実行は null)
             */
            last_result?: ("ok" | "partial" | "error") | null;
            /**
             * Logs
             * @default []
             */
            logs: string[];
            last_transfer?: components["schemas"]["TransferSnapshot"] | null;
        };
        /**
         * TextInputContent
         * @description A text fragment in a multimodal user message.
         */
        TextInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Tool
         * @description A tool definition.
         */
        Tool: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolCall
         * @description A tool call, modelled after OpenAI tool calls.
         */
        ToolCall: {
            /** Id */
            id: string;
            /**
             * Type
             * @default function
             * @constant
             */
            type: "function";
            function: components["schemas"]["FunctionCall"];
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolMessage
         * @description A tool result message.
         */
        ToolMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string;
            /** Toolcallid */
            toolCallId: string;
            /** Error */
            error?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TransferBucket
         * @description ソース別転送統計 1 バケット。
         */
        TransferBucket: {
            /** Requests */
            requests: number;
            /** Bytes Downloaded */
            bytes_downloaded: number;
            /** Bytes Uploaded */
            bytes_uploaded: number;
            /** Bytes Downloaded Mb */
            bytes_downloaded_mb: number;
            /** Bytes Uploaded Mb */
            bytes_uploaded_mb: number;
            /** Direct Requests */
            direct_requests: number;
            /** Proxy Requests */
            proxy_requests: number;
            /** Restricted Hits */
            restricted_hits: number;
            /** Errors */
            errors: number;
        };
        /** TransferPack */
        TransferPack: {
            /**
             * By Source
             * @default {}
             */
            by_source: {
                [key: string]: components["schemas"]["TransferBucket"];
            };
            total: components["schemas"]["TransferBucket"];
        };
        /**
         * TransferSnapshot
         * @description スクレイプ HTTP 転送メトリクスのスナップショット。
         */
        TransferSnapshot: {
            lifetime: components["schemas"]["TransferPack"];
            session?: components["schemas"]["TransferPack"] | null;
            /** Session Label */
            session_label?: string | null;
            /** Session Started At */
            session_started_at?: number | null;
        };
        /**
         * UserMessage
         * @description A user message supporting text or multimodal content.
         */
        UserMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | (components["schemas"]["TextInputContent"] | components["schemas"]["ImageInputContent"] | components["schemas"]["AudioInputContent"] | components["schemas"]["VideoInputContent"] | components["schemas"]["DocumentInputContent"] | components["schemas"]["BinaryInputContent"])[];
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoInputContent
         * @description A video input content fragment.
         */
        VideoInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    copilotkit_agent_endpoint_api_copilotkit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilotkit_health_api_copilotkit_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_chat_threads_api_chat_threads_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_thread_messages_api_chat_threads__thread_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadMessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_thread_api_chat_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frontend_settings_api_fe_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeSettingsResponse"];
                };
            };
        };
    };
    save_frontend_settings_api_fe_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_viewer__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_geojson_api_api_geojson_get: {
        parameters: {
            query?: {
                prefecture_name?: string | null;
                max_monthly_total_yen?: number | null;
                max_walk_minutes?: number | null;
                min_area_m2?: number | null;
                required_features?: string | null;
                saved_only?: boolean;
                exclude_hidden?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyGeoJSON"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geojson_api_map_geojson_get: {
        parameters: {
            query?: {
                prefecture_name?: string | null;
                max_monthly_total_yen?: number | null;
                max_walk_minutes?: number | null;
                min_area_m2?: number | null;
                required_features?: string | null;
                saved_only?: boolean;
                exclude_hidden?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyGeoJSON"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geojson_stream_api_api_geojson_stream_get: {
        parameters: {
            query?: {
                prefecture_name?: string | null;
                max_monthly_total_yen?: number | null;
                max_walk_minutes?: number | null;
                min_area_m2?: number | null;
                required_features?: string | null;
                saved_only?: boolean;
                exclude_hidden?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_kml_api_api_export_kml_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KmlExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_property_detail_api_api_properties__property_id__get: {
        parameters: {
            query?: {
                by?: string;
                source?: string | null;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_price_trend_api_api_analysis_price_trend_get: {
        parameters: {
            query?: {
                /** @description 集計期間(日数)。今日から遡る */
                days?: number;
                /** @description この都道府県の物件のみで集計する */
                prefecture_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceTrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shortlist_api_api_properties__property_id__shortlist_post: {
        parameters: {
            query?: {
                by?: string;
                source?: string | null;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShortlistUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortlistUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_status_api_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
        };
    };
    get_admin_sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourcesResponse"];
                };
            };
        };
    };
    get_admin_scrape_settings_api_admin_scrape_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeSettingsResponse"];
                };
            };
        };
    };
    save_admin_scrape_settings_api_admin_scrape_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scrape_api_admin_scrape_post: {
        parameters: {
            query?: {
                /** @description Single source id or 'all' */
                source?: string | null;
                pages?: number | null;
                all_pages?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScrapeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rotation_status_api_admin_rotation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationStatusResponse"];
                };
            };
        };
    };
    trigger_rotation_run_api_admin_rotation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationRunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_rotation_settings_api_admin_rotation_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSettingsResponse"];
                };
            };
        };
    };
    save_admin_rotation_settings_api_admin_rotation_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_geocode_api_admin_geocode_post: {
        parameters: {
            query?: {
                limit?: number | null;
                force?: boolean;
                provider?: string | null;
                retry_only?: boolean;
                /** @description Removed: filter_expr is no longer supported (v2) */
                filter_expr?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_api_tiles__code___z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
