"""PG baseline — v5 相当スキーマの PostgreSQL 版 (SQLite→PG移行 Phase 1)。

SQLite SCHEMA_VERSION 5 (src/store/schema.py 旧 DDL_STATEMENTS) を PG 型へ
書き直した全 18 テーブル + 14 インデックス。docs/sqlite-pg-migration-plan.md
§3.2(D2)/§3.3(D3 最小差分) に基づく:

- AUTOINCREMENT → ``GENERATED BY DEFAULT AS IDENTITY``(データ移行は明示 id
  INSERT 可 + 移行後に setval)
- REAL → DOUBLE PRECISION(SQLite REAL は float8 相当)
- 時刻 TEXT ISO8601 / ブール INTEGER 0/1 / JSON TEXT はそのまま維持(正規化は
  Phase 6 の別リビジョン)
- properties.building_id の FK を正式化(旧 SQLite は ALTER 制限で FK なし。
  ON DELETE SET NULL — 名寄せバッチは再割当て後に建物を削除するため SET NULL
  が発火するのは孤児掃除時のみで安全)
- schema_meta は feature_dict_hash の KV として存続(版管理は alembic_version
  に一元化し schema_version キーは使わない)
- テーブル定義順は FK 参照先を先に作成(PG は前方参照不可)

Revision ID: pg_baseline
Revises:
Create Date: 2026-10-09

"""

from typing import Sequence, Union

from alembic import op

revision: str = "pg_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = [
    # feature_dict_hash の KV(版管理は alembic_version・schema_version は不使用)
    """
    CREATE TABLE schema_meta (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    )
    """,
    # 建物単位集約モデル B1 (docs/building-aggregation-design.md §4)
    """
    CREATE TABLE buildings (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        canonical_name TEXT,
        address_key TEXT NOT NULL UNIQUE,
        prefecture_slug TEXT,
        prefecture_name TEXT,
        municipality TEXT,
        address TEXT,
        lat DOUBLE PRECISION,
        lng DOUBLE PRECISION,
        geocode_source TEXT,
        geocode_confidence DOUBLE PRECISION,
        built_year INTEGER,
        structure TEXT,
        building_floors INTEGER,
        building_orientation_deg INTEGER,
        is_active INTEGER NOT NULL DEFAULT 1,
        min_daily_rent_yen INTEGER,
        min_plan_total_yen INTEGER,
        units_count INTEGER,
        active_units_count INTEGER,
        first_seen_at TEXT,
        last_seen_at TEXT
    )
    """,
    """
    CREATE TABLE building_names (
        building_id INTEGER NOT NULL,
        source_site TEXT NOT NULL,
        name TEXT NOT NULL,
        UNIQUE(building_id, source_site, name),
        FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE building_shortlists (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        building_id INTEGER NOT NULL UNIQUE,
        status TEXT NOT NULL,
        comment TEXT,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE properties (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_site TEXT NOT NULL,
        external_id TEXT NOT NULL,
        entity_type TEXT NOT NULL DEFAULT 'room',
        parent_property_id INTEGER,
        building_id INTEGER,
        title TEXT,
        detail_url TEXT,
        prefecture_slug TEXT,
        prefecture_name TEXT,
        municipality TEXT,
        address TEXT,
        lat DOUBLE PRECISION,
        lng DOUBLE PRECISION,
        geocode_source TEXT,
        geocode_confidence DOUBLE PRECISION,
        layout TEXT,
        area_m2 DOUBLE PRECISION,
        area_m2_max DOUBLE PRECISION,
        built_year INTEGER,
        built_month INTEGER,
        construction_year_text TEXT,
        capacity_text TEXT,
        structure TEXT,
        floors_text TEXT,
        floor_number INTEGER,
        floor_number_max INTEGER,
        building_floors INTEGER,
        orientation_text TEXT,
        orientation_deg INTEGER,
        orientation_source TEXT,
        point_text TEXT,
        availability_text TEXT,
        min_stay_days INTEGER,
        contract_fee_yen INTEGER,
        first_seen_at TEXT,
        last_seen_at TEXT,
        detail_scraped_at TEXT,
        is_active INTEGER NOT NULL DEFAULT 1,
        catalog_rent_per_day_yen INTEGER,
        catalog_total_hint_yen INTEGER,
        total_score DOUBLE PRECISION DEFAULT 0.0,
        rent_score DOUBLE PRECISION DEFAULT 0.0,
        walk_score DOUBLE PRECISION DEFAULT 0.0,
        area_score DOUBLE PRECISION DEFAULT 0.0,
        age_score DOUBLE PRECISION DEFAULT 0.0,
        commute_score DOUBLE PRECISION DEFAULT 0.0,
        UNIQUE(source_site, external_id),
        FOREIGN KEY(parent_property_id) REFERENCES properties(id) ON DELETE SET NULL,
        FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE property_accesses (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        line_name TEXT,
        station_name TEXT,
        walk_minutes INTEGER,
        raw_text TEXT,
        sort_order INTEGER,
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE property_images (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        image_url TEXT NOT NULL,
        image_type TEXT,
        alt_text TEXT,
        sort_order INTEGER,
        scraped_at TEXT,
        UNIQUE(property_id, image_url),
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE property_links (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        link_type TEXT NOT NULL,
        url TEXT NOT NULL,
        label TEXT,
        scraped_at TEXT,
        UNIQUE(property_id, link_type, url),
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE property_features (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        feature_name TEXT NOT NULL,
        category TEXT,
        UNIQUE(property_id, feature_name),
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE price_plans (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        plan_key TEXT NOT NULL,
        plan_name TEXT,
        duration_min_days INTEGER NOT NULL DEFAULT 1,
        duration_max_days INTEGER,
        available INTEGER NOT NULL DEFAULT 1,
        presentation_unit TEXT NOT NULL DEFAULT 'per_day'
            CHECK(presentation_unit IN ('per_day','per_month')),
        rent_original_yen INTEGER,
        rent_current_yen INTEGER,
        management_yen INTEGER,
        utilities_yen INTEGER,
        utilities_included INTEGER NOT NULL DEFAULT 1,
        cleaning_yen INTEGER,
        campaign_label TEXT,
        raw_text TEXT,
        scraped_at TEXT,
        UNIQUE(property_id, plan_key),
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE campaigns (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        campaign_type TEXT,
        title TEXT,
        content TEXT,
        target_period_text TEXT,
        target_condition_text TEXT,
        starts_on TEXT,
        ends_on TEXT,
        target_plan_key TEXT,
        discount_unit TEXT,
        discount_value INTEGER,
        discount_max_yen INTEGER,
        period_max_days INTEGER,
        stay_min_days INTEGER,
        stay_max_days INTEGER,
        contract_within_days INTEGER,
        package_rent_benefit_yen INTEGER,
        package_cleaning_benefit_yen INTEGER,
        package_fee_benefit_yen INTEGER,
        package_total_benefit_yen INTEGER,
        structure_source TEXT,
        parse_ok INTEGER DEFAULT 0,
        parse_warnings TEXT,
        raw_json TEXT,
        scraped_at TEXT,
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE property_snapshots (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL,
        scraped_at TEXT NOT NULL,
        is_active INTEGER,
        catalog_rent_per_day_yen INTEGER,
        min_discounted_monthly_total_yen INTEGER,
        raw_list_json TEXT,
        raw_detail_json TEXT,
        raw_html_path TEXT,
        parser_version TEXT,
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE raw_pages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_site TEXT NOT NULL,
        url TEXT NOT NULL,
        page_type TEXT NOT NULL,
        fetched_at TEXT NOT NULL,
        status_code INTEGER,
        content_hash TEXT,
        storage_path TEXT,
        parser_version TEXT
    )
    """,
    """
    CREATE TABLE property_shortlists (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property_id INTEGER NOT NULL UNIQUE,
        status TEXT NOT NULL,
        comment TEXT,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE scrape_runs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_site TEXT NOT NULL,
        started_at TEXT NOT NULL,
        finished_at TEXT,
        status TEXT NOT NULL DEFAULT 'running',
        list_pages INTEGER DEFAULT 0,
        list_items INTEGER DEFAULT 0,
        detail_ok INTEGER DEFAULT 0,
        detail_fail INTEGER DEFAULT 0,
        error_summary TEXT,
        meta_json TEXT
    )
    """,
    """
    CREATE TABLE scrape_run_targets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id INTEGER NOT NULL,
        source_site TEXT NOT NULL,
        target_key TEXT NOT NULL,
        started_at TEXT,
        finished_at TEXT,
        status TEXT NOT NULL DEFAULT 'running',
        list_pages INTEGER DEFAULT 0,
        list_items INTEGER DEFAULT 0,
        detail_ok INTEGER DEFAULT 0,
        detail_fail INTEGER DEFAULT 0,
        error_summary TEXT,
        list_completed INTEGER DEFAULT 0,
        FOREIGN KEY(run_id) REFERENCES scrape_runs(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE rotation_state (
        source_site TEXT NOT NULL,
        prefecture_slug TEXT NOT NULL,
        known_total INTEGER,
        last_full_ok_at TEXT,
        last_run_at TEXT,
        consecutive_failures INTEGER DEFAULT 0,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (source_site, prefecture_slug)
    )
    """,
    """
    CREATE TABLE app_settings (
        key TEXT PRIMARY KEY,
        value_json TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
]

_INDEXES = [
    "CREATE INDEX idx_v2_properties_site_id ON properties(source_site, external_id)",
    "CREATE INDEX idx_v2_properties_prefecture ON properties(prefecture_name)",
    "CREATE INDEX idx_v2_properties_pref_slug ON properties(source_site, prefecture_slug)",
    "CREATE INDEX idx_v2_properties_active ON properties(is_active)",
    "CREATE INDEX idx_v2_properties_source ON properties(source_site)",
    "CREATE INDEX idx_features_cat_prop ON property_features(category, property_id)",
    "CREATE INDEX idx_properties_building ON properties(building_id)",
    "CREATE INDEX idx_v2_price_plans_prop ON price_plans(property_id)",
    "CREATE INDEX idx_v2_campaigns_prop ON campaigns(property_id)",
    "CREATE INDEX idx_v2_accesses_prop ON property_accesses(property_id)",
    "CREATE INDEX idx_v2_snapshots_prop ON property_snapshots(property_id)",
    "CREATE INDEX idx_v2_scrape_runs_source ON scrape_runs(source_site, started_at)",
    "CREATE INDEX idx_srt_source_target ON scrape_run_targets(source_site, target_key, finished_at)",
    "CREATE INDEX idx_rotation_state_site ON rotation_state(source_site)",
]


def upgrade() -> None:
    for ddl in _TABLES:
        op.execute(ddl)
    for ddl in _INDEXES:
        op.execute(ddl)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS app_settings, rotation_state, scrape_run_targets,"
               " scrape_runs, property_shortlists, raw_pages, property_snapshots,"
               " campaigns, price_plans, property_features, property_links,"
               " property_images, property_accesses, properties,"
               " building_shortlists, building_names, buildings, schema_meta CASCADE")
