import type { LayerCatalogEntry } from './types';

/**
 * レイヤカタログ。ズーム値は地理院地図の公式レイヤ定義
 * (refs/gsi-layers/gsi_layers*.txt, gsi_hazard.txt)の実値に準拠。
 * maxZoom は一律 20 とし、実解像度は maxNativeZoom で表現する
 * (公式より広いズームでは拡大表示 = 設計doc §4.3 の方針)。
 */
const GSI = 'https://cyberjapandata.gsi.go.jp/xyz';
const HAZARD = 'https://disaportaldata.gsi.go.jp/raster';
const GSI_ATTR =
  '出典: <a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">国土地理院</a>';
const HAZARD_ATTR =
  '出典: <a href="https://disaportal.gsi.go.jp/hazardmapportal/hazardmap/copyright/opendata.html" target="_blank" rel="noopener">国土数値情報(ハザードマップポータル)</a>';
const OSHIMA_ATTR =
  '出典: <a href="https://www.oshimaland.co.jp/" target="_blank" rel="noopener">大島てる</a>';

export const LAYER_CATALOG: LayerCatalogEntry[] = [
  // ── ベースマップ(上部タブ = selectBase ショートカット) ──
  {
    id: 'dark',
    name: 'ダークモード (CARTO)',
    tags: ['basemap'],
    adapter: 'tile',
    role: 'base',
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
    urlTemplate: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    subdomains: 'abcd',
    maxNativeZoom: 20,
    maxZoom: 20,
  },
  {
    id: 'pale',
    name: '淡色地図 (国土地理院)',
    tags: ['basemap'],
    adapter: 'tile',
    role: 'base',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/pale/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 18,
    maxZoom: 20,
  },
  {
    id: 'std',
    name: '標準地図 (国土地理院)',
    tags: ['basemap'],
    adapter: 'tile',
    role: 'base',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/std/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 18,
    maxZoom: 20,
  },
  {
    id: 'satellite',
    name: '衛星写真 (国土地理院)',
    tags: ['basemap', 'photo'],
    adapter: 'tile',
    role: 'base',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/seamlessphoto/{z}/{x}/{y}.jpg`,
    minZoom: 2,
    maxNativeZoom: 18,
    maxZoom: 20,
  },

  // ── 基本地図系オーバーレイ ──
  {
    id: 'blank',
    name: '白地図',
    tags: ['basemap'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/blank/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 14,
    maxZoom: 20,
  },

  // ── 写真・衛星 ──
  {
    id: 'airphoto',
    name: '簡易空中写真 (2004年〜)',
    tags: ['photo'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/airphoto/{z}/{x}/{y}.jpg`,
    minZoom: 5,
    maxNativeZoom: 18,
    maxZoom: 20,
  },
  {
    id: 'nendophoto2017',
    name: '全国写真 2017年',
    tags: ['photo', 'history'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/nendophoto2017/{z}/{x}/{y}.jpg`,
    minZoom: 14,
    maxNativeZoom: 18,
    maxZoom: 20,
  },
  {
    id: 'nendophoto2019',
    name: '全国写真 2019年',
    tags: ['photo', 'history'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/nendophoto2019/{z}/{x}/{y}.jpg`,
    minZoom: 14,
    maxNativeZoom: 18,
    maxZoom: 20,
  },

  // ── 歴史(年代別空中写真) ──
  {
    id: 'gazo1',
    name: '国土画像情報 (1974-1978)',
    tags: ['history', 'photo'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/gazo1/{z}/{x}/{y}.jpg`,
    minZoom: 10,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    id: 'gazo2',
    name: '国土画像情報 (1979-1983)',
    tags: ['history', 'photo'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/gazo2/{z}/{x}/{y}.jpg`,
    minZoom: 10,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    id: 'gazo3',
    name: '国土画像情報 (1984-1986)',
    tags: ['history', 'photo'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/gazo3/{z}/{x}/{y}.jpg`,
    minZoom: 10,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    id: 'gazo4',
    name: '国土画像情報 (1987-1990)',
    tags: ['history', 'photo'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/gazo4/{z}/{x}/{y}.jpg`,
    minZoom: 10,
    maxNativeZoom: 17,
    maxZoom: 20,
  },

  // ── 標高・起伏 ──
  {
    id: 'relief',
    name: '色別標高図',
    tags: ['terrain'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/relief/{z}/{x}/{y}.png`,
    maxNativeZoom: 15,
    maxZoom: 20,
  },
  {
    id: 'slopemap',
    name: '傾斜量図',
    tags: ['terrain', 'hazard'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/slopemap/{z}/{x}/{y}.png`,
    minZoom: 3,
    maxNativeZoom: 15,
    maxZoom: 20,
  },
  {
    id: 'hillshademap',
    name: '陰影起伏図',
    tags: ['terrain'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/hillshademap/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 16,
    maxZoom: 20,
  },
  {
    id: 'sekishoku',
    name: '赤色立体地図',
    tags: ['terrain'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/sekishoku/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 14,
    maxZoom: 20,
  },

  // ── 土地条件 ──
  {
    id: 'lcm25k_2012',
    name: '土地条件図 (1995年国土数値情報)',
    tags: ['landform'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/lcm25k_2012/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 16,
    maxZoom: 20,
  },
  {
    id: 'lcmfc2',
    name: '治水地形分類図',
    tags: ['landform', 'history'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/lcmfc2/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 16,
    maxZoom: 20,
  },
  {
    id: 'swale',
    name: '明治期の低湿地',
    tags: ['history', 'landform'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/swale/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 16,
    maxZoom: 20,
    defaultOpacity: 0.3,
  },
  {
    id: 'lake1',
    name: '湖沼図',
    tags: ['landform'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/lake1/{z}/{x}/{y}.png`,
    minZoom: 5,
    maxNativeZoom: 17,
    maxZoom: 20,
  },

  // ── 火山 ──
  {
    id: 'vlcd',
    name: '火山土地条件図',
    tags: ['volcano'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/vlcd/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 16,
    maxZoom: 20,
    defaultOpacity: 0.45,
  },
  {
    id: 'vbm',
    name: '火山基本図',
    tags: ['volcano'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/vbm/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
  },

  // ── 災害(活断層) ──
  {
    id: 'afm',
    name: '活断層図 (都市圏活断層図)',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/afm/{z}/{x}/{y}.png`,
    maxNativeZoom: 16,
    maxZoom: 20,
    defaultOpacity: 0.4,
  },

  // ── 磁気(2020.0年値) ──
  {
    id: 'jikizu2020_chijiki_d',
    name: '磁気図2020 (偏角)',
    tags: ['magnetic'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/jikizu2020_chijiki_d/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 13,
    maxZoom: 20,
    defaultOpacity: 0.25,
  },
  {
    id: 'jikizu2020_chijiki_i',
    name: '磁気図2020 (伏角)',
    tags: ['magnetic'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/jikizu2020_chijiki_i/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 8,
    maxZoom: 20,
    defaultOpacity: 0.25,
  },
  {
    id: 'jikizu2020_chijiki_f',
    name: '磁気図2020 (全磁力)',
    tags: ['magnetic'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/jikizu2020_chijiki_f/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 8,
    maxZoom: 20,
    defaultOpacity: 0.25,
  },
  {
    id: 'jikizu2020_chijiki_h',
    name: '磁気図2020 (水平分力)',
    tags: ['magnetic'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/jikizu2020_chijiki_h/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 8,
    maxZoom: 20,
    defaultOpacity: 0.25,
  },
  {
    id: 'jikizu2020_chijiki_z',
    name: '磁気図2020 (鉛直分力)',
    tags: ['magnetic'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/jikizu2020_chijiki_z/{z}/{x}/{y}.png`,
    minZoom: 4,
    maxNativeZoom: 8,
    maxZoom: 20,
    defaultOpacity: 0.25,
  },

  // ── 土地利用 ──
  {
    id: 'lum4bl_2020',
    name: '宅地利用動向調査 (2020)',
    tags: ['landuse'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/lum4bl_2020/{z}/{x}/{y}.png`,
    minZoom: 13,
    maxNativeZoom: 16,
    maxZoom: 20,
  },
  {
    id: 'lum200k',
    name: '20万分1土地利用図 (1982-1983)',
    tags: ['landuse'],
    adapter: 'tile',
    attribution: GSI_ATTR,
    urlTemplate: `${GSI}/lum200k/{z}/{x}/{y}.png`,
    minZoom: 11,
    maxNativeZoom: 14,
    maxZoom: 20,
  },

  // ── 災害(ハザードマップポータル。公式定義は minZoom2/maxZoom17) ──
  {
    id: 'flood_l2',
    name: '洪水浸水想定区域 (想定最大規模)',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/01_flood_l2_shinsuishin_data/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    note: '深さごとの浸水ランク表示。浸水しない区域はタイルが存在しない',
    defaultOpacity: 0.6,
  },
  {
    id: 'flood_l1',
    name: '洪水浸水想定区域 (計画規模)',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/01_flood_l1_shinsuishin_newlegend_data/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    note: '計画規模(現在の凡例)。浸水しない区域はタイルが存在しない',
    defaultOpacity: 0.6,
  },
  {
    id: 'tsunami',
    name: '津波浸水想定 (想定最大規模)',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/04_tsunami_newlegend_data/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    defaultOpacity: 0.6,
  },
  {
    id: 'kyukeisha',
    name: '急傾斜地の崩壊警戒区域',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/05_kyukeishakeikaikuiki/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    note: '黄=警戒区域, 赤=特別警戒区域',
    defaultOpacity: 0.6,
  },
  {
    id: 'dosekiryu',
    name: '土石流警戒区域',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/05_dosekiryukeikaikuiki/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    note: '黄=警戒区域, 赤=特別警戒区域',
    defaultOpacity: 0.5,
  },
  {
    id: 'jisuberi',
    name: '地すべり警戒区域',
    tags: ['hazard'],
    adapter: 'tile',
    attribution: HAZARD_ATTR,
    urlTemplate: `${HAZARD}/05_jisuberikeikaikuiki/{z}/{x}/{y}.png`,
    minZoom: 2,
    maxNativeZoom: 17,
    maxZoom: 20,
    note: '黄=警戒区域, 赤=特別警戒区域',
    defaultOpacity: 0.5,
  },

  // ── 防災・避難(オシマランド。アダプタは feat/layers-oshima で登録) ──
  {
    id: 'oshima',
    name: '大島てる (事故物件マーク)',
    tags: ['safety'],
    adapter: 'oshima',
    attribution: OSHIMA_ATTR,
    note: '非公式API。クラスタリング無効時はズーム12未満で非表示。1時間キャッシュ',
    defaultOpacity: 1,
    settings: ['defaultOpacity', 'clustering'],
  },
];

export const catalogById: ReadonlyMap<string, LayerCatalogEntry> = new Map(
  LAYER_CATALOG.map((entry) => [entry.id, entry]),
);

/** カタログのうち未有効のレイヤ(無効リスト表示用)。タグ→名前順 */
export function disabledEntries(enabledIds: ReadonlySet<string>): LayerCatalogEntry[] {
  return LAYER_CATALOG.filter((entry) => !enabledIds.has(entry.id)).sort((a, b) => {
    const tagA = a.tags[0] ?? 'zz';
    const tagB = b.tags[0] ?? 'zz';
    if (tagA !== tagB) return tagA < tagB ? -1 : 1;
    return a.name.localeCompare(b.name, 'ja');
  });
}
