import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

/**
 * TanStack Router entry (Phase R1).
 * Routes live under `src/routes/`; the tree is generated by
 * `@tanstack/router-plugin` into `routeTree.gen.ts`.
 *
 * `/` search params: checkIn, checkOut, priceMode, id, compare, view.
 */
export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  scrollRestoration: true,
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
